"""Generated unit test stub for tool 'escalate-to-investigator'.

DO NOT EDIT BY HAND -- generated by the Output Packager (Stage 5) from the
tool's declared schema (Section 4.3). Wire up the real import below once
your project's package layout is finalized.
"""

from __future__ import annotations

import pytest

TOOL_ID = "escalate-to-investigator"
EXPECTED_SIDE_EFFECTS = "irreversible"
EXPECTED_TIMEOUT_MS = 10000
EXPECTED_AUTH_SCOPES = ['case:escalate']


@pytest.mark.skip(reason="wire up the real tool module import for your project layout")
def test_tool_binding_matches_spec():
    # TODO: from src.tools import escalate_to_investigator as tool_module
    # assert tool_module.SIDE_EFFECTS == EXPECTED_SIDE_EFFECTS
    # assert tool_module.TIMEOUT_MS == EXPECTED_TIMEOUT_MS
    # assert tool_module.AUTH_SCOPES == EXPECTED_AUTH_SCOPES
    raise NotImplementedError
