"""Generated unit test stub for tool 'create-case-record'.

DO NOT EDIT BY HAND -- generated by the Output Packager (Stage 5) from the
tool's declared schema (Section 4.3). Wire up the real import below once
your project's package layout is finalized.
"""

from __future__ import annotations

import pytest

TOOL_ID = "create-case-record"
EXPECTED_SIDE_EFFECTS = "write"
EXPECTED_TIMEOUT_MS = 12000
EXPECTED_AUTH_SCOPES = ['case:write']


@pytest.mark.skip(reason="wire up the real tool module import for your project layout")
def test_tool_binding_matches_spec():
    # TODO: from src.tools import create_case_record as tool_module
    # assert tool_module.SIDE_EFFECTS == EXPECTED_SIDE_EFFECTS
    # assert tool_module.TIMEOUT_MS == EXPECTED_TIMEOUT_MS
    # assert tool_module.AUTH_SCOPES == EXPECTED_AUTH_SCOPES
    raise NotImplementedError
