"""Generated unit test stub for tool 'get-transaction-history'.

DO NOT EDIT BY HAND -- generated by the Output Packager (Stage 5) from the
tool's declared schema (Section 4.3). Wire up the real import below once
your project's package layout is finalized.
"""

from __future__ import annotations

import pytest

TOOL_ID = "get-transaction-history"
EXPECTED_SIDE_EFFECTS = "read"
EXPECTED_TIMEOUT_MS = 8000
EXPECTED_AUTH_SCOPES = ['fraud:read', 'txn:read']


@pytest.mark.skip(reason="wire up the real tool module import for your project layout")
def test_tool_binding_matches_spec():
    # TODO: from src.tools import get_transaction_history as tool_module
    # assert tool_module.SIDE_EFFECTS == EXPECTED_SIDE_EFFECTS
    # assert tool_module.TIMEOUT_MS == EXPECTED_TIMEOUT_MS
    # assert tool_module.AUTH_SCOPES == EXPECTED_AUTH_SCOPES
    raise NotImplementedError
