"""Generated contract test stub for tool 'get-transaction-history'.

DO NOT EDIT BY HAND -- generated by the Output Packager (Stage 5). Confirms
the declared tool schema (Section 4.3) matches the behavior of its live
endpoint once wired up (Section 9: contract tests).
"""

from __future__ import annotations

import pytest

TOOL_ID = "get-transaction-history"
TOOL_SCHEMA = {'type': 'object', 'required': ['customerId', 'lookbackDays'], 'properties': {'customerId': {'type': 'string'}, 'lookbackDays': {'type': 'integer'}}}


@pytest.mark.skip(reason="wire up the live endpoint for 'get-transaction-history' before enabling")
def test_live_endpoint_matches_declared_schema():
    # TODO: call the live 'get-transaction-history' endpoint and validate its
    # response against TOOL_SCHEMA (e.g. with jsonschema.validate).
    raise NotImplementedError
