"""Generated contract test stub for tool 'create-case-record'.

DO NOT EDIT BY HAND -- generated by the Output Packager (Stage 5). Confirms
the declared tool schema (Section 4.3) matches the behavior of its live
endpoint once wired up (Section 9: contract tests).
"""

from __future__ import annotations

import pytest

TOOL_ID = "create-case-record"
TOOL_SCHEMA = {'type': 'object', 'required': ['alertId', 'narrative', 'recommendation'], 'properties': {'alertId': {'type': 'string'}, 'narrative': {'type': 'string'}, 'recommendation': {'type': 'string'}}}


@pytest.mark.skip(reason="wire up the live endpoint for 'create-case-record' before enabling")
def test_live_endpoint_matches_declared_schema():
    # TODO: call the live 'create-case-record' endpoint and validate its
    # response against TOOL_SCHEMA (e.g. with jsonschema.validate).
    raise NotImplementedError
